# Generated by Django 6.0 on 2025-12-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('DOCUMENTS', 'Important Documents'), ('VEHICLES', 'Vehicles'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, help_text='Physical storage location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Manufacturer serial number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
